### ISSUE TITLE
the accuracy of the 2d lidar and camera

### ISSUE THREAD

**Issue by yuyadanyadan** [TurtleZhong/Projects-Summary#1]
Hi, how is your accuracy of 2d lidar and camera???   the degree is +- 0.5 degree of roll and pitch;  And the accuracy is not enough for my system.  thank you very much!

**Comment by TurtleZhong** [comment]
The calibration accuracy depends on many factors. This project was completed during my internship. At that time, the accuracy requirements of the external parameters were not too high, so I did not specifically measure the accuracy of the calibration results, but we manually selected some key points to judge the quality of the calibration.. I guess the degree is +- 1 degree of roll,pitch and yaw. For some reason, I have not release the code. So...

**Comment by TurtleZhong** [comment]
> Hi, how is your accuracy of 2d lidar and camera??? the degree is +- 0.5 degree of roll and pitch; And the accuracy is not enough for my system. thank you very much!

@yuyadanyadan The calibration accuracy depends on many factors. This project was completed during my internship. At that time, the accuracy requirements of the external parameters were not too high, so I did not specifically measure the accuracy of the calibration results, but we manually selected some key points to judge the quality of the calibration.. I guess the degree is +- 1 degree of roll,pitch and yaw. For some reason, I have not release the code. So...

**Comment by yuyadanyadan** [comment]
ok, thanks

**Comment by yuyadanyadan** [comment]
ok, thanks

**Comment by yuyadanyadan** [comment]
> > Hi, how is your accuracy of 2d lidar and camera??? the degree is +- 0.5 degree of roll and pitch; And the accuracy is not enough for my system. thank you very much!
> 
> @yuyadanyadan The calibration accuracy depends on many factors. This project was completed during my internship. At that time, the accuracy requirements of the external parameters were not too high, so I did not specifically measure the accuracy of the calibration results, but we manually selected some key points to judge the quality of the calibration.. I guess the degree is +- 1 degree of roll,pitch and yaw. For some reason, I have not release the code. So...

ok, thanks
